app.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: onlinebook-deployment
  namespace: app
spec:
  selector:
    matchLabels:
      app: onlinebook
  replicas: 2
  template:
    metadata:
      labels:
        app: onlinebook
    spec:
      containers:
      - name: onlinebook
        image: nishanth0/onlinebook
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: onlinebook
  namespace: app
spec:
  selector:
    app: onlinebook
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 32001

kubectl port-forward service/onlinebook -n app --address 0.0.0.0 8080:8080
*** we can access the application using public_ip: port_number
